In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://query.data.world/s/rxwrus2odpb6cwjddwdjpbb5djcnln")
df.head(5)

   STT   T1   L1   H1   S1   V1   X1  ...  GT  DT   KV   DH1   DH2   DH3  KT
0    1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F NaN  2NT  3.25  3.25  4.50  A1
1    2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M NaN    1  6.00  4.00  3.50   C
2    3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M NaN    1  5.00  6.75  4.00   C
3    4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M NaN    1  4.25  4.25  5.25  D1
4    5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M NaN  2NT  4.25  4.50  5.00   A

[5 rows x 56 columns]

In [ ]:
df = df.drop(['T3', 'L3', 'H3', 'V3', 'S3', 'X3', 'D3', 'N3'], axis=1)
df = df.drop(['T4', 'L4', 'H4', 'V4', 'S4', 'X4', 'D4', 'N4'], axis=1)
df = df.drop(['T5', 'L5', 'H5', 'V5', 'S5', 'X5', 'D5', 'N5'], axis=1)
df = df.drop(['STT'], axis=1)

In [ ]:
df = df.rename(columns={"T1": "TOAN10", "L1": "LY10", "H1": "HOA10", "S1": "SINH10", "V1": "VAN10", "X1": "SU10", "D1": "DIA10", "N1": "NGOAI NGU10"})
df = df.rename(columns={"T2": "TOAN11", "L2": "LY11", "H2": "HOA11", "S2": "SINH11", "V2": "VAN11", "X2": "SU11", "D2": "DIA11", "N2": "NGOAI NGU11"})
df = df.rename(columns={"T6": "TOAN12", "L6": "LY12", "H6": "HOA12", "S6": "SINH12", "V6": "VAN12", "X6": "SU12", "D6": "DIA12", "N6": "NGOAI NGU12"})
df = df.rename(columns={"GT": "GIOI TINH", "DT": "DAN TOC", "KV": "KHU VUC THI", "KT": "KHOI THI", "DH1": "DIEM THI MON 1", "DH2": "DIEM THI MON 2", "DH3": "DIEM THI MON 3",})

In [ ]:
df.head(3)

   TOAN10  LY10  HOA10  ...  DIEM THI MON 2  DIEM THI MON 3  KHOI THI
0     7.2   7.3    6.3  ...            3.25             4.5        A1
1     5.4   3.9    3.9  ...            4.00             3.5         C
2     5.6   6.8    7.2  ...            6.75             4.0         C

[3 rows x 31 columns]

In [ ]:
df['TBM1'] = (df['TOAN10']*2 + df['LY10'] + df['HOA10'] + df['SINH10'] + df['VAN10']*2 + df['SU10'] + df['DIA10'] + df['NGOAI NGU10'])/10
df['TBM2'] = (df['TOAN11']*2 + df['LY11'] + df['HOA11'] + df['SINH11'] + df['VAN11']*2 + df['SU11'] + df['DIA11'] + df['NGOAI NGU11'])/10
df['TBM3'] = (df['TOAN12']*2 + df['LY12'] + df['HOA12'] + df['SINH12'] + df['VAN12']*2 + df['SU12'] + df['DIA12'] + df['NGOAI NGU12'])/10
df.head(3)

   TOAN10  LY10  HOA10  SINH10  ...  KHOI THI  TBM1  TBM2  TBM3
0     7.2   7.3    6.3     7.3  ...        A1  7.00  7.54  7.01
1     5.4   3.9    3.9     4.0  ...         C  4.69  5.47  5.07
2     5.6   6.8    7.2     7.5  ...         C  5.77  5.38  6.04

[3 rows x 34 columns]

In [ ]:
df['XL1'] = ''
df['XL2'] = ''
df['XL3'] = ''

In [ ]:
df.loc[(df['TBM1']) < 5, 'XL1'] = 'Y'
df.loc[(df['TBM1']) >= 5, 'XL1'] = 'TB'
df.loc[(df['TBM1']) >= 6.5, 'XL1'] = 'K'
df.loc[(df['TBM1']) >= 8, 'XL1'] = 'G'
df.loc[(df['TBM1']) >= 9, 'XL1'] = 'XS'

In [ ]:
df.loc[(df['TBM2']) < 5, 'XL2'] = 'Y'
df.loc[(df['TBM2']) >= 5, 'XL2'] = 'TB'
df.loc[(df['TBM2']) >= 6.5, 'XL2'] = 'K'
df.loc[(df['TBM2']) >= 8, 'XL2'] = 'G'
df.loc[(df['TBM2']) >= 9, 'XL2'] = 'XS'

In [ ]:
df.loc[(df['TBM3']) < 5, 'XL3'] = 'Y'
df.loc[(df['TBM3']) >= 5, 'XL3'] = 'TB'
df.loc[(df['TBM3']) >= 6.5, 'XL3'] = 'K'
df.loc[(df['TBM3']) >= 8, 'XL3'] = 'G'
df.loc[(df['TBM3']) >= 9, 'XL3'] = 'XS'

In [ ]:
df.head(15)

    TOAN10  LY10  HOA10  SINH10  VAN10  SU10  ...  TBM1  TBM2  TBM3  XL1  XL2  XL3
0      7.2   7.3    6.3     7.3    7.0   7.9  ...  7.00  7.54  7.01    K    K    K
1      5.4   3.9    3.9     4.0    5.4   5.4  ...  4.69  5.47  5.07    Y   TB   TB
2      5.6   6.8    7.2     7.5    4.3   7.4  ...  5.77  5.38  6.04   TB   TB   TB
3      6.6   6.4    5.3     6.9    5.4   7.3  ...  6.21  5.20  6.88   TB   TB    K
4      6.0   5.0    6.0     7.3    6.5   7.7  ...  6.50  6.36  6.99    K   TB    K
5      9.3   7.6    7.9     8.6    7.0   7.3  ...  7.96  8.54  7.38    K    G    K
6      2.8   3.9    5.5     6.9    5.0   7.3  ...  4.90  5.60  6.01    Y   TB   TB
7      8.3   6.0    7.6     5.1    7.5   4.7  ...  6.80  6.87  7.03    K    K    K
8      6.5   6.3    7.6     6.0    5.5   7.1  ...  6.23  6.72  7.56   TB    K    K
9      7.3   5.9    4.7     7.1    6.7   7.9  ...  6.80  7.25  7.03    K    K    K
10     5.2   6.4    7.4     7.0    7.1   8.1  ...  6.79  7.28  7.34    K    K    K
11     7.9   7.0    9.1     8.6    6.1   7.0  ...  7.43  7.72  7.49    K    K    K
12     7.3   6.3    8.7     7.7    6.6   8.5  ...  7.44  6.82  7.46    K    K    K
13     4.9   5.4    5.0     5.0    5.8   7.0  ...  5.38  5.51  6.26   TB   TB   TB
14     7.1   8.0    9.1     7.5    6.1   7.7  ...  7.42  7.57  7.95    K    K    K

[15 rows x 37 columns]

In [ ]:
def normalize(x):
    return x*0.4

In [ ]:
df['US_TBM1'] = normalize(df['TBM1'])
df['US_TBM2'] = normalize(df['TBM2'])
df['US_TBM3'] = normalize(df['TBM3'])
df.head(5)

   TOAN10  LY10  HOA10  SINH10  VAN10  ...  XL2  XL3  US_TBM1  US_TBM2  US_TBM3
0     7.2   7.3    6.3     7.3    7.0  ...    K    K    2.800    3.016    2.804
1     5.4   3.9    3.9     4.0    5.4  ...   TB   TB    1.876    2.188    2.028
2     5.6   6.8    7.2     7.5    4.3  ...   TB   TB    2.308    2.152    2.416
3     6.6   6.4    5.3     6.9    5.4  ...   TB    K    2.484    2.080    2.752
4     6.0   5.0    6.0     7.3    6.5  ...   TB    K    2.600    2.544    2.796

[5 rows x 40 columns]

In [ ]:
df['KQXT'] = 'ROT'

In [ ]:
for khoi in df['KHOI THI']:
  if khoi == 'A1' and khoi == 'A':
    df.loc[((df['DIEM THI MON 1']*2 + df['DIEM THI MON 2'] + df['DIEM THI MON 3'])/4 >= 5), 'KQXT'] = 'DAU'
  elif khoi == 'B':
    df.loc[((df['DIEM THI MON 1'] + df['DIEM THI MON 2']*2 + df['DIEM THI MON 3'])/4 >= 5), 'KQXT'] = 'DAU'
  else:
    df.loc[((df['DIEM THI MON 1'] + df['DIEM THI MON 2'] + df['DIEM THI MON 3'])/3 >= 5), 'KQXT'] = 'DAU'

df.head(5)

   TOAN10  LY10  HOA10  SINH10  VAN10  ...  XL3  US_TBM1  US_TBM2  US_TBM3  KQXT
0     7.2   7.3    6.3     7.3    7.0  ...    K    2.800    3.016    2.804   ROT
1     5.4   3.9    3.9     4.0    5.4  ...   TB    1.876    2.188    2.028   ROT
2     5.6   6.8    7.2     7.5    4.3  ...   TB    2.308    2.152    2.416   DAU
3     6.6   6.4    5.3     6.9    5.4  ...    K    2.484    2.080    2.752   ROT
4     6.0   5.0    6.0     7.3    6.5  ...    K    2.600    2.544    2.796   ROT

[5 rows x 41 columns]

In [ ]:
df.to_csv('ketquaxettuyendaihoc.csv')